import type { Metadata } from "next";
import "./globals.css";
import {Providers} from "@/app/Providers";
import {Toaster} from "react-hot-toast";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <Providers>
            {children}
            <Toaster />
        </Providers>
        </body>
        </html>
    );
}